[build]
  # custom build command that install bun and run build
  command = "./scripts/build.sh"
  # vite output folder
  publish = "netlify"

[build.environment]
   # disable NPM install
   NPM_FLAGS = "--version"
   VITE_API_URL = "wss://api.federated-learning.madsbuch.com/"